name = 'Air'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Hugo Air Theme'
version = '1.0.1'
screenshot = '/images/screenshot.jpg/

# The home page of the theme, where the source can be found
homepage = 'https://github.com/francoiducat/hugo-air'

# If you have a running demo of the theme
demosite = 'https://francoiducat.github.io/hugo-air'

# Taxonomy terms
tags = ['blog', 'company', 'website', 'portfolio']
features = ['responsive', 'images gallery', 'page bundle gallery', 'masonry image gallery', 'instagram image gallery', 'google maps', 'bootstrap', 'shortcodes']

# If the theme has a single author
[author]
  name = 'francoiducat'
  homepage = 'https://notes.ducatillon.net'
