name = 'Air'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Hugo Air Theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/francoiducat/hugo-air'

# If you have a running demo of the theme
demosite = 'https://yeulocation.ducatillon.net'

# Taxonomy terms
tags = ['blog', 'company', 'website']
features = ['responsive', 'images gallery', 'google maps', 'bootstrap', 'shortcodes']

# If the theme has a single author
[author]
  name = 'francoiducat'
  homepage = 'https://notes.ducatillon.net'
